# Generated by Django 5.1.4 on 2024-12-07 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_phone_number_employee_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='updated_at',
            new_name='modified_on',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='employee',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
