import jsPDF from 'jspdf';
import 'jspdf-autotable';

const generatePDF = (employees, username) => {
    const doc = new jsPDF();
    const generatedBy = `Generated by: ${username}`;
    const generatedOn = `Generated on: ${new Date().toLocaleString()}`;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(generatedBy, 20, 25);
    doc.text(generatedOn, 20, 30);

    doc.setDrawColor(200);
    doc.line(20, 18, 190, 18);

    doc.setTextColor(0);
    doc.setFontSize(16);
    doc.text('Employee List', 20, 10);

    const tableData = employees.map((emp, index) => [
        index + 1,
        emp.name,
        emp.designation,
        emp.phone_number,
        emp.added_by,
        emp.modified_by,
        new Date(emp.created_on).toLocaleString(),
        new Date(emp.modified_on).toLocaleString(),
    ]);

    doc.autoTable({
        head: [
            [
                '#',
                'Name',
                'Designation',
                'Phone Number',
                'Added By',
                'Modified By',
                'Created On',
                'Modified On',
            ],
        ],
        body: tableData,
        startY: 40,
    });

    doc.save('Employee_List.pdf');
};

export default generatePDF;
